# Generated by Django 4.2.4 on 2023-08-24 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="adds_to_favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Избранное",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipes.RecipeIngredientAmount",
                to="recipes.ingredientunit",
                verbose_name="Игриедиенты с ед. измер.",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="shopping_cart_adds",
            field=models.ManyToManyField(
                blank=True,
                related_name="shopping_cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="В корзине",
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", to="recipes.tag", verbose_name="Теги"
            ),
        ),
        migrations.AddField(
            model_name="ingredientunit",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.ingredient",
                verbose_name="Ингредиент",
            ),
        ),
        migrations.AddField(
            model_name="ingredientunit",
            name="measurement_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.measurementunit",
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="measurement_units",
            field=models.ManyToManyField(
                related_name="ingredients",
                through="recipes.IngredientUnit",
                to="recipes.measurementunit",
                verbose_name="Единица измерения",
            ),
        ),
    ]
