# Generated by Django 4.2.4 on 2023-08-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipeingredientamount",
            options={
                "verbose_name": "Ингредиент, ед. измер., кол-во",
                "verbose_name_plural": "Ингредиенты, ед. измер., кол-во",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ("name",),
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
