# Generated by Django 4.2.4 on 2023-09-09 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredientamount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                db_index=True,
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code='invalid name',
                        message='Название тега может состоять только из одного слова, содержащего буквы кириллицы.',
                        regex='^[А-Яа-я]+$',
                    )
                ],
                verbose_name='Название',
            ),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(
                fields=('author', 'name'), name='unique_author_recipe_name'
            ),
        ),
    ]
